# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, verbose_name='BL Number')),
                ('date', models.DateField()),
                ('delivered_by', models.CharField(blank=True, max_length=150, verbose_name='Delivered By')),
                ('received_by_signature', models.TextField(blank=True, verbose_name='Signature (base64)')),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='delivery_notes/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='clients.client')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Price HT')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %')),
                ('cartons', models.PositiveIntegerField(default=0, verbose_name='Cartons')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.deliverynote')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='inventory.variant')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Invoice Number')),
                ('series_prefix', models.CharField(default='FA', max_length=20, verbose_name='Series Prefix')),
                ('date', models.DateField(db_index=True, verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=12, verbose_name='Status')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total HT (ex-TVA)')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='TVA Rate %')),
                ('tva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='TVA Amount')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total TTC (incl. TVA)')),
                ('apply_tva', models.BooleanField(default=True, verbose_name='Apply TVA')),
                ('is_formal', models.BooleanField(default=True, verbose_name='Formal Invoice')),
                ('is_paid_in_cash', models.BooleanField(default=False, verbose_name='Paid in Cash')),
                ('timbre_fiscal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fiscal Stamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='PDF File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='invoicing.invoice'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Credit Note Number')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='credit_notes/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price HT')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %')),
                ('cartons', models.PositiveIntegerField(default=0, verbose_name='Cartons')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.variant')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('ccp', 'CCP'), ('virement', 'Virement')], max_length=10, verbose_name='Method')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='clients.cheque')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='FA', max_length=20)),
                ('year', models.IntegerField()),
                ('last_sequence', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'prefix', 'year')},
            },
        ),
    ]
