# Generated by Django 5.0.6 on 2026-07-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
        ('invoicing', '0002_deliverynote_client_deliverynote_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
    ]
