# Generated by Django 5.0.6 on 2026-07-16 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_alter_deliverynote_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_formal',
            field=models.BooleanField(default=True, verbose_name='Formal Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid_in_cash',
            field=models.BooleanField(default=False, verbose_name='Paid in Cash'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fiscal Stamp'),
        ),
    ]
