# Generated by Django 5.0.6 on 2026-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoice_is_formal_invoice_is_paid_in_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteline',
            name='cartons',
            field=models.PositiveIntegerField(default=0, verbose_name='Cartons'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='cartons',
            field=models.PositiveIntegerField(default=0, verbose_name='Cartons'),
        ),
    ]
