# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Internal Reference')),
                ('category', models.CharField(choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal', 'Formal'), ('sport', 'Sport'), ('kids', 'Kids Shoes'), ('slippers', 'Slippers'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Gender')),
                ('season', models.CharField(choices=[('all', 'All Year'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring_fall', 'Spring / Fall')], default='all', max_length=12, verbose_name='Season')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Purchase Price (DZD)')),
                ('pamp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='PAMP (DZD)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sale Price (DZD)')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Wholesale Price (DZD)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_threshold', models.IntegerField(default=10, verbose_name='Low Stock Alert Threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_eu', models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)], verbose_name='EU Size')),
                ('colour', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Colour')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='Barcode')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Stock Qty')),
                ('alert_threshold', models.IntegerField(default=3, verbose_name='Low Stock Alert Threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Variant (SKU)',
                'verbose_name_plural': 'Variants (SKUs)',
                'ordering': ['product', 'size_eu', 'colour'],
                'unique_together': {('product', 'size_eu', 'colour')},
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=12, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.branch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_delta', models.IntegerField(verbose_name='Quantity Change')),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('reception', 'Stock Reception'), ('adjustment', 'Manual Adjustment'), ('return', 'Customer Return'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('damaged', 'Damaged / Written Off'), ('initial', 'Initial Stock Entry')], max_length=15, verbose_name='Reason')),
                ('reference_id', models.CharField(blank=True, max_length=50, verbose_name='Reference ID')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Reference Type')),
                ('bl_reference', models.CharField(blank=True, max_length=100, verbose_name='BL Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Shelving')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_locations', to='inventory.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Product Location',
                'verbose_name_plural': 'Product Locations',
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
