# Generated by Django 5.0.6 on 2026-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pairs_per_carton',
            field=models.PositiveIntegerField(default=10, verbose_name='Pairs per Carton'),
        ),
    ]
