# Generated by Django 5.0.6 on 2026-08-02 22:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_wilayas_communes'),
        ('inventory', '0002_product_pairs_per_carton'),
        ('suppliers', '0002_poline_pairs_per_carton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity of Pairs')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Cost Price (DZD)')),
                ('defect_reason', models.CharField(choices=[('sole_unglued', 'Semelle décollée'), ('torn_leather', 'Cuir / Tissu déchiré ou rayé'), ('mismatched_size', 'Pointure dépareillée'), ('stitching', 'Couture défectueuse'), ('stain_discolor', 'Tache / Décoloration'), ('missing_accessory', 'Accessoire / Lacet manquant'), ('other', 'Autre anomalie')], default='other', max_length=30, verbose_name='Defect Reason')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defects/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('quarantined', 'En Quarantaine'), ('claim_pending', 'Réclamation Fournisseur en cours'), ('returned', 'Retourné au Fournisseur'), ('sold_discount', 'Vendu Déclassé (2ème choix)'), ('written_off', 'Rebuté / Perte')], default='quarantined', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='core.branch')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_logged', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='suppliers.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Defect Item',
                'verbose_name_plural': 'Defect Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
