# Generated by Django 5.0.6 on 2026-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_bl_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_threshold',
            field=models.IntegerField(default=10, verbose_name='Low Stock Alert Threshold'),
        ),
    ]
