# Generated by Django 5.0.6 on 2026-08-02 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_wilayas_communes'),
        ('inventory', '0003_defectitem'),
        ('suppliers', '0003_supplierreturnclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectitem',
            name='return_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='suppliers.supplierreturnclaim'),
        ),
        migrations.AddField(
            model_name='defectitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='defectitem',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='defectitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='inventory.variant'),
        ),
    ]
