# Generated by Django 5.0.6 on 2026-07-16 15:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pamp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='PAMP (DZD)'),
        ),
    ]
