# Generated by Django 5.0.6 on 2026-08-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_defectitem_return_claim_defectitem_supplier_and_more'),
        ('sales', '0003_exchangereturnitem_defect_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectitem',
            name='sale_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='sales.exchange'),
        ),
        migrations.AddField(
            model_name='defectitem',
            name='sale_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='sales.return'),
        ),
    ]
