# Generated by Django 5.0.6 on 2026-08-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_defectitem_sale_exchange_defectitem_sale_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectitem',
            name='defect_reason',
            field=models.CharField(choices=[('unstitched_sole', 'Semelle décollée / décousue'), ('broken_strap', 'Bride / Lanière cassée'), ('mismatched_pair', 'Paire dépareillée'), ('leather_tear', 'Déchirure cuir / tissu'), ('discoloration', 'Décoloration / Teinte'), ('broken_heel', 'Talon cassé / défectueux'), ('missing_insole', 'Semelle intérieure manquante'), ('other', 'Autre anomalie')], default='other', max_length=30, verbose_name='Defect Reason'),
        ),
    ]
