# Generated by Django 5.0.6 on 2026-08-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_defectitem_defect_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectitem',
            name='defect_reason',
            field=models.CharField(choices=[('sole_unglued', 'Semelle décollée'), ('unstitched_sole', 'Semelle décollée / décousue'), ('broken_strap', 'Bride / Lanière cassée'), ('mismatched_pair', 'Paire dépareillée'), ('mismatched_size', 'Pointure dépareillée'), ('torn_leather', 'Cuir / Tissu déchiré'), ('leather_tear', 'Déchirure cuir / tissu'), ('discoloration', 'Décoloration / Teinte'), ('stain_discolor', 'Tache / Décoloration'), ('broken_heel', 'Talon cassé / défectueux'), ('missing_insole', 'Semelle intérieure manquante'), ('stitching', 'Couture défectueuse'), ('missing_accessory', 'Accessoire / Lacet manquant'), ('other', 'Autre anomalie')], default='other', max_length=30, verbose_name='Defect Reason'),
        ),
    ]
