# Generated by Django 5.0.6 on 2026-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_wholesale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='colour',
            field=models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Colour'),
        ),
    ]
