# Generated by Django 5.0.6 on 2026-07-17 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_variant_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size_eu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)], verbose_name='EU Size'),
        ),
    ]
