# Generated by Django 5.0.6 on 2026-08-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_wilayas_communes'),
        ('inventory', '0007_alter_defectitem_defect_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='core.branch'),
        ),
    ]
