# Generated by Django 5.0.6 on 2026-07-20 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(blank=True, max_length=64)),
                ('license_key', models.CharField(blank=True, max_length=64)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('valid', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'License State',
                'verbose_name_plural': 'License State',
            },
        ),
    ]
