# Generated by Django 5.0.6 on 2026-07-23 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_populate_wilayas_communes'),
        ('sales', '0002_cashreconciliation_movements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('website', 'Website'), ('ouedkniss', 'Ouedkniss'), ('tiktok', 'TikTok'), ('phone', 'Phone Call'), ('manual', 'Manual')], default='whatsapp', max_length=20, verbose_name='Order Source')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('wilaya', models.CharField(blank=True, max_length=50, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('address', models.TextField(blank=True, verbose_name='Detailed Address')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Customer Notes / Requested Items')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed / Ready to Ship'), ('dispatched', 'Dispatched / In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('rejected', 'Rejected / Cancelled'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Shipping Fee')),
                ('provider', models.CharField(blank=True, choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('maystro', 'Maystro Delivery'), ('noest', 'NOEST')], max_length=20, null=True, verbose_name='Delivery Provider')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('maystro', 'Maystro Delivery'), ('noest', 'NOEST')], max_length=20, verbose_name='Provider')),
                ('api_id', models.CharField(blank=True, max_length=255, verbose_name='API ID / Token')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret / Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Delivery Provider Config',
                'verbose_name_plural': 'Delivery Provider Configs',
                'unique_together': {('tenant', 'provider')},
            },
        ),
    ]
