# Generated by Django 5.0.6 on 2026-07-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_wilayas_communes'),
        ('delivery_integrations', '0002_social_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialintegration',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
    ]
