# Generated by Django 5.0.6 on 2026-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_integrations', '0003_alter_socialintegration_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='sender_id',
            field=models.CharField(blank=True, db_index=True, help_text='The external user ID from Meta (Messenger/Instagram) used to merge multi-message orders.', max_length=100, null=True, verbose_name='Sender ID'),
        ),
    ]
