# Generated by Django 5.0.6 on 2026-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Integration API Key'),
        ),
    ]
