# Generated by Django 5.0.6 on 2026-06-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_versement_pct', models.PositiveSmallIntegerField(default=30, help_text='Minimum percentage of sale total required as first payment for versement.', verbose_name='Minimum versement (% of total)')),
                ('versement_due_days', models.PositiveIntegerField(default=90, help_text='Days from first payment before the versement is considered overdue.', verbose_name='Versement due (days)')),
                ('versement_requires_client', models.BooleanField(default=True, verbose_name='Versement requires a linked client')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
