# Generated by Django 5.0.6 on 2026-07-23 14:34

import json
import os
from django.db import migrations
from django.conf import settings

def load_wilayas_and_communes(apps, schema_editor):
    Wilaya = apps.get_model('core', 'Wilaya')
    Commune = apps.get_model('core', 'Commune')
    
    fixtures_dir = os.path.join(settings.BASE_DIR, 'apps', 'core', 'fixtures')
    wilayas_path = os.path.join(fixtures_dir, 'wilayas.json')
    communes_path = os.path.join(fixtures_dir, 'communes.json')
    
    # Load Wilayas
    if os.path.exists(wilayas_path):
        with open(wilayas_path, 'r', encoding='utf-8-sig') as f:
            wilayas_data = json.load(f)
            # The JSON id corresponds to the Wilaya code but we should zero-pad it to 2 digits
            # if we want it to match existing "01", "02" format in the db.
            # However, looking at the JSON, code is "1", "2".
            # Let's zero-pad them so they match the standard 58 Algerian wilaya codes.
            wilaya_objs = []
            for item in wilayas_data:
                code = str(item.get('id')).zfill(2)
                wilaya_objs.append(Wilaya(
                    id=int(item.get('id')),
                    code=code,
                    name=item.get('name'),
                    ar_name=item.get('ar_name')
                ))
            Wilaya.objects.bulk_create(wilaya_objs)
            
    # Load Communes
    if os.path.exists(communes_path):
        with open(communes_path, 'r', encoding='utf-8-sig') as f:
            communes_data = json.load(f)
            
            commune_objs = []
            for item in communes_data:
                commune_objs.append(Commune(
                    id=int(item.get('id')),
                    wilaya_id=int(item.get('wilaya_id')),
                    post_code=item.get('post_code', ''),
                    name=item.get('name'),
                    ar_name=item.get('ar_name')
                ))
            Commune.objects.bulk_create(commune_objs)

def unload_wilayas_and_communes(apps, schema_editor):
    Wilaya = apps.get_model('core', 'Wilaya')
    Commune = apps.get_model('core', 'Commune')
    Commune.objects.all().delete()
    Wilaya.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wilaya_commune'),
    ]

    operations = [
        migrations.RunPython(load_wilayas_and_communes, reverse_code=unload_wilayas_and_communes),
    ]
