# Generated by Django 5.0.6 on 2026-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='pairs_per_carton',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
