# Generated by Django 5.0.6 on 2026-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='cartons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
