# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('category', models.CharField(blank=True, help_text='Match variants whose product.category equals this value. Leave blank to match any category.', max_length=100, verbose_name='Category')),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Promotion applies only when the cart line has at least this many units.', null=True, verbose_name='Minimum quantity')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Promotion applies only when unit_price × qty ≥ this amount.', max_digits=10, null=True, verbose_name='Minimum line amount (DZD)')),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount, e.g. 15 → 15% off the line total.', max_digits=5, null=True, verbose_name='Discount %')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount per unit in DZD, e.g. 500 → 500 DZD off per unit.', max_digits=10, null=True, verbose_name='Discount per unit (DZD)')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = wins when multiple promotions match the same line.', verbose_name='Priority')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total number of sale lines this promotion can be applied to. Null = unlimited.', null=True, verbose_name='Max uses')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Uses count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Restrict to a specific product. Overrides category filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='inventory.product', verbose_name='Product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', 'start_date'],
            },
        ),
    ]
