# Generated by Django 5.0.6 on 2026-07-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_bl_reference'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Restrict to a specific product. Overrides category filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='inventory.product', verbose_name='Product'),
        ),
    ]
