# Generated by Django 5.0.6 on 2026-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], db_index=True, default='retail', max_length=10, verbose_name='Client Type'),
        ),
    ]
