# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(default=0, verbose_name='Points balance')),
                ('total_earned', models.IntegerField(default=0, verbose_name='Lifetime points earned')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or')], default='bronze', max_length=10, verbose_name='Tier')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='clients.client', verbose_name='Client')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Account',
                'verbose_name_plural': 'Loyalty Accounts',
                'unique_together': {('tenant', 'client')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_per_100dzd', models.PositiveIntegerField(default=1, help_text='Base points earned per 100 DZD spent (before tier multiplier).', verbose_name='Points per 100 DZD')),
                ('redemption_value', models.PositiveIntegerField(default=100, help_text='Points required to get 100 DZD off.', verbose_name='Points needed for 100 DZD')),
                ('min_redemption_points', models.PositiveIntegerField(default=500, verbose_name='Minimum redeemable points')),
                ('silver_threshold', models.PositiveIntegerField(default=5000, verbose_name='Silver tier threshold (lifetime pts)')),
                ('gold_threshold', models.PositiveIntegerField(default=15000, verbose_name='Gold tier threshold (lifetime pts)')),
                ('silver_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=4, verbose_name='Silver tier earn multiplier')),
                ('gold_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, verbose_name='Gold tier earn multiplier')),
                ('expiry_months', models.PositiveIntegerField(blank=True, help_text='Set to null to never expire points.', null=True, verbose_name='Point expiry (months)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(help_text='Positive = earned; negative = redeemed / expired.', verbose_name='Points')),
                ('transaction_type', models.CharField(choices=[('earn', 'Gain'), ('redeem', 'Rachat'), ('adjust', 'Ajustement'), ('expire', 'Expiration')], max_length=10, verbose_name='Type')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Reference type')),
                ('reference_id', models.CharField(blank=True, max_length=50, verbose_name='Reference ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('balance_after', models.IntegerField(verbose_name='Balance after')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
