# Generated by Django 5.0.6 on 2026-06-07 20:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='gold_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, verbose_name='Gold tier earn multiplier'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='gold_threshold',
            field=models.PositiveIntegerField(default=15000, verbose_name='Gold tier threshold (lifetime pts)'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='silver_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=4, verbose_name='Silver tier earn multiplier'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='silver_threshold',
            field=models.PositiveIntegerField(default=5000, verbose_name='Silver tier threshold (lifetime pts)'),
        ),
    ]
