# Generated by Django 5.0.6 on 2026-07-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
    ]
