# Generated by Django 5.0.6 on 2026-07-20 12:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('extra_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Extra Payment')),
                ('extra_payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('ccp', 'CCP (Algérie Poste)'), ('virement', 'Virement Bancaire'), ('account', 'Client Account Balance')], max_length=10, verbose_name='Extra Payment Method')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cash Refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Exchange',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeNewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_items', to='sales.exchange')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_new_items', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Exchange New Item',
            },
        ),
        migrations.CreateModel(
            name='ExchangeReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original Unit Price')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='sales.exchange')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_returns', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Exchange Return Item',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='Reason')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund Amount')),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('ccp', 'CCP (Algérie Poste)'), ('virement', 'Virement Bancaire'), ('account', 'Client Account Balance')], default='cash', max_length=10, verbose_name='Refund Method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('restock', models.BooleanField(default=True, verbose_name='Return to Stock')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Return Item',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_paid', 'Partially Paid')], default='completed', max_length=15, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (DZD)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cart Discount')),
                ('is_formal', models.BooleanField(default=False, verbose_name='Formal Invoice')),
                ('timbre_fiscal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fiscal Stamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Receipt Number')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.branch')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.client')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('ccp', 'CCP (Algérie Poste)'), ('virement', 'Virement Bancaire'), ('account', 'Client Account Balance')], max_length=10, verbose_name='Method')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cheque_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='clients.cheque')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='exchange',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='sales.sale'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price (DZD)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Discount')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Sale Item',
            },
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé')], default='pending', max_length=20, verbose_name='Status')),
                ('system_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_ccp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_virement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_sales_count', models.PositiveIntegerField(default=0)),
                ('system_total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_ccp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_virement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='core.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cash Reconciliation',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('tenant', 'date', 'branch')},
            },
        ),
    ]
