# Generated by Django 5.0.6 on 2026-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Due Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_paid', 'Partially Paid')], default='completed', max_length=15, verbose_name='Status'),
        ),
    ]
