# Generated by Django 5.0.6 on 2026-06-08 00:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
        ('sales', '0002_sale_due_date_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé')], default='pending', max_length=20, verbose_name='Status')),
                ('system_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_ccp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_virement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('system_sales_count', models.PositiveIntegerField(default=0)),
                ('system_total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_ccp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_virement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='core.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cash Reconciliation',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('tenant', 'date', 'branch')},
            },
        ),
    ]
