# Generated by Django 5.0.6 on 2026-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cashreconciliation_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangereturnitem',
            name='defect_notes',
            field=models.TextField(blank=True, default='', verbose_name='Defect Notes'),
        ),
        migrations.AddField(
            model_name='exchangereturnitem',
            name='defect_reason',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Defect Reason'),
        ),
        migrations.AddField(
            model_name='exchangereturnitem',
            name='is_defective',
            field=models.BooleanField(default=False, verbose_name='Is Defective'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='defect_notes',
            field=models.TextField(blank=True, default='', verbose_name='Defect Notes'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='defect_reason',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Defect Reason'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='is_defective',
            field=models.BooleanField(default=False, verbose_name='Is Defective'),
        ),
    ]
