# Generated by Django 5.0.6 on 2026-06-09 12:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
        ('inventory', '0001_initial'),
        ('sales', '0003_cash_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('extra_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Extra Payment')),
                ('extra_payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('ccp', 'CCP (Algérie Poste)'), ('virement', 'Virement Bancaire'), ('account', 'Client Account Balance')], max_length=10, verbose_name='Extra Payment Method')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cash Refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='sales.sale')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Exchange',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeNewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_items', to='sales.exchange')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_new_items', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Exchange New Item',
            },
        ),
        migrations.CreateModel(
            name='ExchangeReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original Unit Price')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='sales.exchange')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_returns', to='inventory.variant')),
            ],
            options={
                'verbose_name': 'Exchange Return Item',
            },
        ),
    ]
